name: sda
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Core
  - python=3.9.16
  - pip=22.3.1
  - numpy=1.23.5
  - scipy=1.10.1
  - h5py=3.7.0
  - jupyter=1.0.0

  # PyTorch + CUDA
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7

  # Explicit runtime deps (from the resolver chase)
  - requests
  - typing_extensions=4.12.2
  - contourpy=1.0.7
  - cycler=0.12.1
  - fonttools=4.55.3
  - kiwisolver=1.4.7
  - packaging=24.2
  - python-dateutil=2.9.0.post0
  - pandas=1.5.3

  # pip-installed packages
  - pip:
      # your original list
      - dawgz==0.4.1
      - jax==0.4.13
      - jaxlib==0.4.13
      - zuko==0.1.4
      - wandb==0.13.10
      - tqdm==4.64.1
      - matplotlib==3.6.2
      - seaborn==0.12.2
      - POT==0.9.0

      # JAX runtime deps
      - ml_dtypes==0.5.1
      - opt_einsum==3.3.0
      - importlib_metadata>=4.6

      # W&B runtime deps
      - docker-pycreds==0.4.0
      - GitPython==3.1.44
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4

      # Torchvision runtime dep
      - pillow==10.4.0
      - typing_extensions==4.7.1
